### ISSUE TITLE
Confusion about multi-class MRF

### ISSUE THREAD

**Issue by hnisonoff** [locuslab/sdp_mrf#1]
Hi quick question. I noticed in the paper and examples here the multi-class MRF seems to have a bias vector that has shape (n,k) but the pairwise interactions are of shape (n,n). Apologies if this is dumb question, but shouldn't the interaction matrix be of shape (n,k, n,k). To put it another way, for most MRFs there are interaction terms that depend on the class of the nodes not just the positions of the nodes?

**Comment by chogba** [comment]
The [Wikipedia article](https://en.wikipedia.org/wiki/Potts_model) for the Potts model specifies the standard formulation for pairwise interactions in terms of the Kronecker delta function, as we did in our work. We did incorporate a separate coefficient for each class in the bias vector as a modeling choice -- this formulation for the bias generalizes that in the wikipedia article. However, it seems plausible to model pairwise interactions differently for different pairs of classes, like you suggested -- seems like that would have more expressive power!

**Comment by hnisonoff** [comment]
Thanks for the reply. I was hoping to try this method out but I do need separate coefficients for each class. It does make sense that some problems (especially motivated by physics / vision) would not use separate coefficients.

**Comment by chogba** [comment]
It feels like it should be possible to write down the expression for the probability distribution with different coefficients, and write down the MAP inference optimization problem+mixing-method updates for that too --- although I admit I have not thought about it much. I would suggest looking into how the quadratic form inside the exp() would have to change for this, and then seeing if it is in a form amenable to performing coordinate-ascent updates that we do in our paper!

**Comment by hnisonoff** [comment]
If you write the input as one-hot-encoded categorical vectors then everything can be written as a quadratic form:
`x^T A x + h^T x`

Where A is size (n*k, n*k) and h is size (nk, 1)

I haven't looked close enough to your paper to understand how this will modify the coordinate-ascent updates.
